/// LC3 Assembly code generator.
use but_grammar::ast::{
    Condition, ModelDefinition, ModelPart, Property, SourceUnit, SourceUnitPart, StatePart,
};

use crate::behavior::{model_composition, find_end_property, find_terminal_states, BehaviorKind};
use crate::condition::condition_to_c;
use crate::ltl::{extract_ltl_formulas, ltl_comments_asm};
use crate::CodegenContext;

/// Generate combined LC3 assembly for all models from a SourceUnit.
pub fn generate_lc3_all(source: &SourceUnit, ctx: &CodegenContext) -> String {
    let mut out = String::new();
    out.push_str("; Generated by but-codegen (LC3 assembly)\n");
    out.push_str("; All models combined in one file\n\n");
    out.push_str(".ORIG x3000\n\n");

    let mut has_models = false;
    for part in &source.0 {
        if let SourceUnitPart::ModelDefinition(md) = part {
            out.push_str(&generate_lc3_model_body(md, ctx));
            out.push('\n');
            has_models = true;
        }
    }

    if !has_models {
        out.push_str("; (no models)\n");
    }

    out.push_str("\n.END\n");
    out
}

/// Generate LC3 assembly for a single model.
pub fn generate_lc3(model: &ModelDefinition, ctx: &CodegenContext) -> String {
    let mut out = String::new();
    out.push_str("; Generated by but-codegen (LC3 assembly)\n");
    let ltl_formulas = extract_ltl_formulas(model);
    if !ltl_formulas.is_empty() {
        out.push_str(&ltl_comments_asm(&ltl_formulas));
    }
    out.push_str(".ORIG x3000\n\n");
    out.push_str(&generate_lc3_model_body(model, ctx));
    out.push_str("\n.END\n");
    out
}

// ── Internal generation of a single model body ────────────────────────────────────

fn generate_lc3_model_body(model: &ModelDefinition, ctx: &CodegenContext) -> String {
    let ltl_formulas = extract_ltl_formulas(model);
    if let Some(bk) = model_composition(model) {
        generate_lc3_behavior(model, &bk, ctx, &ltl_formulas)
    } else {
        generate_lc3_fsm(model, ctx, &ltl_formulas)
    }
}

fn generate_lc3_fsm(
    model: &ModelDefinition,
    _ctx: &CodegenContext,
    ltl_formulas: &[String],
) -> String {
    let name = model_name(model).to_uppercase();
    let states = collect_states(model);
    let start = find_start(model).unwrap_or_else(|| states.first().cloned().unwrap_or_default());
    let start_idx = states.iter().position(|s| *s == start).unwrap_or(0) as i64;
    let terminal_states = find_terminal_states(model);
    let end_prop = find_end_property(model);

    let mut out = String::new();
    out.push_str(&format!("; === Model: {} ===\n", name));
    if !ltl_formulas.is_empty() {
        out.push_str(&ltl_comments_asm(ltl_formulas));
    }

    // Initialization
    out.push_str(&format!("; Initialization: {}\n", name));
    out.push_str(&format!("{}_INIT\n", name));
    out.push_str(&format!("    LD R0, {}_STATE_INIT\n", name));
    out.push_str(&format!("    ST R0, {}_STATE\n\n", name));

    // is_done flag initialization
    if !terminal_states.is_empty() {
        out.push_str(&format!("    AND R0, R0, #0\n"));
        out.push_str(&format!("    ST R0, {}_DONE\n\n", name));
    }

    // Main loop
    out.push_str(&format!("; Main loop: {}\n", name));
    out.push_str(&format!("{}_LOOP\n", name));
    out.push_str(&format!("    LD R0, {}_STATE\n", name));

    for (idx, sname) in states.iter().enumerate() {
        out.push_str(&format!("    ; Check state {}\n", sname));
        out.push_str(&format!("    LD R1, {}_CONST_{}\n", name, idx));
        out.push_str("    NOT R2, R1\n");
        out.push_str("    ADD R2, R2, #1\n");
        out.push_str("    ADD R2, R0, R2\n");
        out.push_str(&format!("    BRz {}_STATE_{}\n", name, sname.to_uppercase()));
    }
    out.push_str(&format!("    BRnzp {}_LOOP\n\n", name));

    // State handlers
    for (idx, sname) in states.iter().enumerate() {
        let is_terminal = terminal_states.iter().any(|t| t == sname);
        out.push_str(&format!("; State: {} (idx={})\n", sname, idx));
        out.push_str(&format!("{}_STATE_{}\n", name, sname.to_uppercase()));

        if let Some(ModelPart::StateDefinition(sd)) = model.parts.iter().find(|p| {
            if let ModelPart::StateDefinition(sd) = p {
                sd.name.as_ref().map(|n| n.name.as_str()) == Some(sname.as_str())
            } else {
                false
            }
        }) {
            for sp in &sd.parts {
                if let StatePart::Reference(_, target, cond) = sp {
                    let cond_comment = cond
                        .as_ref()
                        .map(|c| format!("condition: {}", condition_to_c(c)))
                        .unwrap_or_else(|| "unconditional".to_string());
                    out.push_str(&format!("    ; {}\n", cond_comment));
                    let target_idx = states.iter().position(|s| s == &target.name).unwrap_or(0);
                    out.push_str(&format!("    LD R3, {}_CONST_{}\n", name, target_idx));
                    out.push_str(&format!("    ST R3, {}_STATE\n", name));
                    out.push_str(&format!("    BRnzp {}_LOOP\n", name));
                }
            }
        }

        // Terminal state: is_done = 1 + end handler
        if is_terminal {
            out.push_str(&format!("    ; Terminal state — set done flag\n"));
            out.push_str(&format!("    AND R0, R0, #0\n"));
            out.push_str(&format!("    ADD R0, R0, #1\n"));
            out.push_str(&format!("    ST R0, {}_DONE\n", name));
            if end_prop.is_some() {
                out.push_str(&format!("    ; end handler — see {}_END_HANDLER\n", name));
                out.push_str(&format!("    JSR {}_END_HANDLER\n", name));
            }
        }

        out.push_str(&format!("    BRnzp {}_LOOP\n\n", name));
    }

    // End handler subroutine
    if let Some(ep) = end_prop {
        out.push_str(&format!("; End handler subroutine: {}\n", name));
        out.push_str(&format!("{}_END_HANDLER\n", name));
        match ep {
            Property::Expression(e) => {
                out.push_str(&format!(
                    "    ; end: {}\n",
                    crate::condition::expr_to_c(e)
                ));
            }
            Property::Function(_) => {
                out.push_str("    ; end block (implement manually)\n");
            }
        }
        out.push_str("    RET\n\n");
    }

    // Data
    out.push_str(&format!("; Data: {}\n", name));
    out.push_str(&format!("{}_STATE .BLKW 1\n", name));
    out.push_str(&format!("{}_STATE_INIT .FILL #{}\n", name, start_idx));
    if !terminal_states.is_empty() {
        out.push_str(&format!("{}_DONE .BLKW 1\n", name));
    }
    for (i, _) in states.iter().enumerate() {
        out.push_str(&format!("{}_CONST_{} .FILL #{}\n", name, i, i));
    }
    out
}

fn generate_lc3_behavior(
    model: &ModelDefinition,
    bk: &BehaviorKind,
    _ctx: &CodegenContext,
    ltl_formulas: &[String],
) -> String {
    let name = model_name(model).to_uppercase();
    let models = bk.models();
    let end_prop = find_end_property(model);
    let mut out = String::new();

    out.push_str(&format!("; === Composition model: {} ===\n", name));
    if !ltl_formulas.is_empty() {
        out.push_str(&ltl_comments_asm(ltl_formulas));
    }

    let kind_str = match bk {
        BehaviorKind::Sequential(_) => "sequential",
        BehaviorKind::Parallel(_) => "parallel",
        BehaviorKind::Choice(_) => "choice",
    };
    out.push_str(&format!("; Composition type: {} ({})\n", kind_str, models.join(", ")));
    out.push_str(&format!("; Sub-models: {}\n\n", models.join(", ")));

    // Initialization
    out.push_str(&format!("{}_COMP_INIT\n", name));
    for m in models {
        out.push_str(&format!("    JSR {}_INIT\n", m.to_uppercase()));
    }
    out.push_str(&format!("    AND R0, R0, #0\n"));
    out.push_str(&format!("    ST R0, {}_PHASE\n\n", name));

    // Step
    out.push_str(&format!("{}_COMP_STEP\n", name));
    match bk {
        BehaviorKind::Sequential(ms) => {
            for (i, m) in ms.iter().enumerate() {
                out.push_str(&format!(
                    "    ; Phase {}: {}\n    LD R0, {}_PHASE\n    LD R1, {}_CONST_{}\n    NOT R2, R1\n    ADD R2, R2, #1\n    ADD R2, R0, R2\n    BRz {}_DO_{}\n",
                    i, m, name, name, i, name, m.to_uppercase()
                ));
            }
            for (i, m) in ms.iter().enumerate() {
                out.push_str(&format!("{}_DO_{}\n", name, m.to_uppercase()));
                out.push_str(&format!("    JSR {}_STEP\n", m.to_uppercase()));
                out.push_str(&format!("    LD R0, {}_DONE\n", m.to_uppercase()));
                out.push_str(&format!("    BRz {}_STEP_DONE\n", name));
                let next_phase = i + 1;
                out.push_str(&format!("    LD R0, {}_CONST_{}\n", name, next_phase));
                out.push_str(&format!("    ST R0, {}_PHASE\n", name));
                if i + 1 == ms.len() {
                    if end_prop.is_some() {
                        out.push_str(&format!("    JSR {}_END_HANDLER\n", name));
                    }
                }
                out.push_str(&format!("    BRnzp {}_STEP_DONE\n", name));
            }
        }
        BehaviorKind::Parallel(ms) => {
            for m in ms {
                out.push_str(&format!("    LD R0, {}_DONE\n", m.to_uppercase()));
                out.push_str(&format!("    BRnz {}_SKIP_{}\n", name, m.to_uppercase()));
                out.push_str(&format!("    JSR {}_STEP\n", m.to_uppercase()));
                out.push_str(&format!("{}_SKIP_{}\n", name, m.to_uppercase()));
            }
            if end_prop.is_some() {
                out.push_str(&format!("    ; Check completion of all sub-models\n"));
                for m in ms {
                    out.push_str(&format!("    LD R0, {}_DONE\n    BRz {}_STEP_DONE\n", m.to_uppercase(), name));
                }
                out.push_str(&format!("    JSR {}_END_HANDLER\n", name));
            }
        }
        BehaviorKind::Choice(ms) => {
            if let Some(m) = ms.first() {
                out.push_str(&format!("    JSR {}_STEP\n", m.to_uppercase()));
                out.push_str(&format!("    LD R0, {}_DONE\n", m.to_uppercase()));
                out.push_str(&format!("    BRz {}_STEP_DONE\n", name));
                if end_prop.is_some() {
                    out.push_str(&format!("    JSR {}_END_HANDLER\n", name));
                }
            }
        }
    }
    out.push_str(&format!("{}_STEP_DONE\n    RET\n\n", name));

    // End handler
    if let Some(ep) = end_prop {
        out.push_str(&format!("; End handler: {}\n", name));
        out.push_str(&format!("{}_END_HANDLER\n", name));
        match ep {
            Property::Expression(e) => {
                out.push_str(&format!(
                    "    ; end: {}\n",
                    crate::condition::expr_to_c(e)
                ));
            }
            Property::Function(_) => {
                out.push_str("    ; end block (implement manually)\n");
            }
        }
        out.push_str("    RET\n\n");
    }

    // Data
    out.push_str(&format!("; Data: {}\n", name));
    out.push_str(&format!("{}_PHASE .BLKW 1\n", name));
    for (i, _) in models.iter().enumerate() {
        out.push_str(&format!("{}_CONST_{} .FILL #{}\n", name, i, i));
    }
    out.push_str(&format!(
        "{}_CONST_{} .FILL #{}\n",
        name,
        models.len(),
        models.len()
    ));
    out
}

// ── Helper functions ─────────────────────────────────────────────────────────────

fn model_name(model: &ModelDefinition) -> String {
    model.name.as_ref().map(|n| n.name.clone()).unwrap_or_else(|| "MODEL".to_string())
}

fn collect_states(model: &ModelDefinition) -> Vec<String> {
    model.parts.iter().filter_map(|p| {
        if let ModelPart::StateDefinition(sd) = p {
            sd.name.as_ref().map(|n| n.name.clone())
        } else {
            None
        }
    }).collect()
}

fn find_start(model: &ModelDefinition) -> Option<String> {
    for part in &model.parts {
        match part {
            ModelPart::PropertyDefinition(pd) => {
                if pd.name.as_ref().map(|n| n.name.as_str()) == Some("start") {
                    if let Property::Expression(but_grammar::ast::Expression::Variable(id)) = &pd.value {
                        return Some(id.name.clone());
                    }
                }
            }
            ModelPart::ConditionDefinition(cd) => {
                if cd.name.as_ref().map(|n| n.name.as_str()) == Some("start") {
                    if let Condition::Variable(id) = &cd.value {
                        return Some(id.name.clone());
                    }
                }
            }
            _ => {}
        }
    }
    None
}
