/// Structured Text (IEC 61131-3) code generator.
use but_grammar::ast::{
    Condition, ModelDefinition, ModelPart, Property, SourceUnit, SourceUnitPart, StatePart,
    VariableAttribute,
};

use crate::behavior::{model_composition, find_end_property, find_terminal_states, BehaviorKind};
use crate::condition::{condition_to_c, expr_to_c, stmt_to_c, type_to_st_ctx};
use crate::ltl::{extract_ltl_formulas, ltl_comments_st};
use crate::CodegenContext;

// ── Public API ────────────────────────────────────────────────────────────────

/// Generate a combined ST declarations file for all models.
pub fn generate_st_decl_all(source: &SourceUnit, ctx: &CodegenContext) -> String {
    let mut out = String::new();
    out.push_str("(* Generated by but-codegen *)\n\n");
    for part in &source.0 {
        if let SourceUnitPart::ModelDefinition(md) = part {
            out.push_str(&generate_st_model_decl(md, ctx));
            out.push('\n');
        }
    }
    out
}

/// Generate a combined ST program file for all models.
pub fn generate_st_prog_all(source: &SourceUnit, ctx: &CodegenContext) -> String {
    let mut out = String::new();
    out.push_str("(* Generated by but-codegen *)\n\n");
    for part in &source.0 {
        if let SourceUnitPart::ModelDefinition(md) = part {
            out.push_str(&generate_st_model_prog(md, ctx));
            out.push('\n');
        }
    }
    out
}

/// Generate a combined ST output `(decl, prog)` — one declarations file and one program file.
pub fn generate_st_all(source: &SourceUnit, ctx: &CodegenContext) -> (String, String) {
    (generate_st_decl_all(source, ctx), generate_st_prog_all(source, ctx))
}

/// Generate a declarations file for a single model (for direct use in tests).
pub fn generate_st_decl(model: &ModelDefinition, ctx: &CodegenContext) -> String {
    generate_st_model_decl(model, ctx)
}

/// Generate a program file for a single model (for direct use in tests).
pub fn generate_st_program(model: &ModelDefinition, ctx: &CodegenContext) -> String {
    generate_st_model_prog(model, ctx)
}

// ── Declaration generation ──────────────────────────────────────────────────────────

fn generate_st_model_decl(model: &ModelDefinition, ctx: &CodegenContext) -> String {
    let name = model_name(model).to_uppercase();
    let i1 = ctx.indent.level(1);
    let mut out = String::new();

    let ltl_formulas = extract_ltl_formulas(model);
    if !ltl_formulas.is_empty() {
        out.push_str(&ltl_comments_st(&ltl_formulas));
    }

    out.push_str(&format!("FUNCTION_BLOCK {}\n", name));
    out.push_str("VAR\n");

    let behavior = model_composition(model);
    if let Some(bk) = &behavior {
        // Composition model: phase variable + sub-model instances
        match bk {
            BehaviorKind::Sequential(models) | BehaviorKind::Choice(models) => {
                out.push_str(&format!("{}phase : INT := 0;\n", i1));
                out.push_str(&format!("{}done : BOOL := FALSE;\n", i1));
                for m in models {
                    out.push_str(&format!("{}{} : {};\n", i1, m.to_lowercase(), m.to_uppercase()));
                }
            }
            BehaviorKind::Parallel(models) => {
                out.push_str(&format!("{}done : BOOL := FALSE;\n", i1));
                for m in models {
                    out.push_str(&format!("{}{} : {};\n", i1, m.to_lowercase(), m.to_uppercase()));
                }
            }
        }
    } else {
        // Regular FSM
        out.push_str(&format!("{}state : INT;\n", i1));

        // Ports
        for vd in &ctx.global_vars {
            if vd.attrs.iter().any(|a| matches!(a, VariableAttribute::Portable(_))) {
                if let Some(vname) = &vd.name {
                    let ty = type_to_st_ctx(&vd.ty, &ctx.type_aliases);
                    let init = vd
                        .initializer
                        .as_ref()
                        .map(|e| expr_to_c(e))
                        .unwrap_or_else(|| "0".to_string());
                    let dir = if vd.attrs.iter().any(|a| matches!(a, VariableAttribute::Readable(_))) {
                        "AT %I"
                    } else {
                        "AT %Q"
                    };
                    out.push_str(&format!("{}{} {} : {} := {};\n", i1, vname.name, dir, ty, init));
                }
            }
        }

        // Model variables
        for part in &model.parts {
            if let ModelPart::VariableDefinition(vd) = part {
                if vd.attrs.iter().any(|a| matches!(a, VariableAttribute::Portable(_))) {
                    continue;
                }
                if let Some(vname) = &vd.name {
                    let ty = type_to_st_ctx(&vd.ty, &ctx.type_aliases);
                    let init = vd
                        .initializer
                        .as_ref()
                        .map(|e| expr_to_c(e))
                        .unwrap_or_else(|| "0".to_string());
                    out.push_str(&format!("{}{} : {} := {};\n", i1, vname.name, ty, init));
                }
            }
        }

        // is_done flag (if there are terminal states)
        let terminals = find_terminal_states(model);
        if !terminals.is_empty() {
            out.push_str(&format!("{}is_done : BOOL := FALSE;\n", i1));
        }
    }

    out.push_str("END_VAR\n");
    out
}

// ── Program generation ───────────────────────────────────────────────────────────────

fn generate_st_model_prog(model: &ModelDefinition, ctx: &CodegenContext) -> String {
    if let Some(bk) = model_composition(model) {
        generate_st_behavior_prog(model, &bk, ctx)
    } else {
        generate_st_fsm_prog(model, ctx)
    }
}

fn generate_st_fsm_prog(model: &ModelDefinition, ctx: &CodegenContext) -> String {
    let name = model_name(model).to_uppercase();
    let states = collect_states(model);
    let start = find_start(model).unwrap_or_else(|| states.first().cloned().unwrap_or_default());
    let i1 = ctx.indent.level(1);
    let i2 = ctx.indent.level(2);
    let i3 = ctx.indent.level(3);

    let terminal_states = find_terminal_states(model);
    let end_prop = find_end_property(model);

    let mut out = String::new();
    out.push_str(&format!("(* Program: {} *)\n", name));

    for (i, s) in states.iter().enumerate() {
        out.push_str(&format!("(* {}_STATE_{} = {} *)\n", name, s.to_uppercase(), i));
    }

    let start_idx = states.iter().position(|s| *s == start).unwrap_or(0);
    out.push_str(&format!("\n(* Initialize *)\n"));
    out.push_str(&format!("IF state = 0 AND state < 0 THEN\n"));
    out.push_str(&format!("{}state := {};\n", i1, start_idx));
    out.push_str("END_IF;\n\n");

    // Global enter handlers
    for part in &model.parts {
        if let ModelPart::PropertyDefinition(pd) = part {
            if pd.name.as_ref().map(|n| n.name.as_str()) == Some("enter") {
                match &pd.value {
                    Property::Expression(e) => {
                        out.push_str(&format!("(* global enter *) {} ;\n", expr_to_c(e)));
                    }
                    Property::Function(s) => {
                        out.push_str(&stmt_to_c(s, &ctx.indent, 0));
                    }
                }
            }
        }
    }

    out.push_str("\n(* State machine *)\n");
    out.push_str("CASE state OF\n");

    for (idx, state_name) in states.iter().enumerate() {
        let is_terminal = terminal_states.iter().any(|t| t == state_name);
        out.push_str(&format!("{}{} : (* {} *)\n", i1, idx, state_name));

        if let Some(ModelPart::StateDefinition(sd)) = model.parts.iter().find(|p| {
            if let ModelPart::StateDefinition(sd) = p {
                sd.name.as_ref().map(|n| n.name.as_str()) == Some(state_name.as_str())
            } else {
                false
            }
        }) {
            // Enter
            for sp in &sd.parts {
                if let StatePart::PropertyDefinition(pd) = sp {
                    if pd.name.as_ref().map(|n| n.name.as_str()) == Some("enter") {
                        match &pd.value {
                            Property::Expression(e) => {
                                out.push_str(&format!("{}{} ;\n", i2, expr_to_c(e)));
                            }
                            Property::Function(s) => {
                                out.push_str(&stmt_to_c(s, &ctx.indent, 2));
                            }
                        }
                    }
                }
            }

            // Transitions
            for sp in &sd.parts {
                if let StatePart::Reference(_, target, cond) = sp {
                    let cond_str = cond
                        .as_ref()
                        .map(|c| condition_to_c(c))
                        .unwrap_or_else(|| "TRUE".to_string());
                    let target_idx = states
                        .iter()
                        .position(|s| s == &target.name)
                        .unwrap_or(states.len());

                    out.push_str(&format!("{}IF {} THEN\n", i2, cond_str));

                    for sp2 in &sd.parts {
                        if let StatePart::PropertyDefinition(pd2) = sp2 {
                            if pd2.name.as_ref().map(|n| n.name.as_str()) == Some("exit") {
                                match &pd2.value {
                                    Property::Expression(e) => {
                                        out.push_str(&format!("{}{} ;\n", i3, expr_to_c(e)));
                                    }
                                    Property::Function(s) => {
                                        out.push_str(&stmt_to_c(s, &ctx.indent, 3));
                                    }
                                }
                            }
                        }
                    }

                    out.push_str(&format!("{}state := {};\n", i3, target_idx));
                    out.push_str(&format!("{}END_IF;\n", i2));
                }
            }

            // Terminal state: end handler + is_done
            if is_terminal {
                if !terminal_states.is_empty() {
                    out.push_str(&format!("{}is_done := TRUE;\n", i2));
                }
                if let Some(ep) = end_prop {
                    out.push_str(&format!("{}(* end handler *)\n", i2));
                    match ep {
                        Property::Expression(e) => {
                            out.push_str(&format!("{}{} ;\n", i2, expr_to_c(e)));
                        }
                        Property::Function(s) => {
                            out.push_str(&stmt_to_c(s, &ctx.indent, 2));
                        }
                    }
                }
            }
        }

        out.push('\n');
    }

    out.push_str("END_CASE;\n");
    out
}

fn generate_st_behavior_prog(
    model: &ModelDefinition,
    bk: &BehaviorKind,
    ctx: &CodegenContext,
) -> String {
    let name = model_name(model).to_uppercase();
    let i1 = ctx.indent.level(1);
    let i2 = ctx.indent.level(2);
    let models = bk.models();
    let end_prop = find_end_property(model);
    let mut out = String::new();

    out.push_str(&format!("(* Program: {} *)\n", name));

    match bk {
        BehaviorKind::Sequential(_) => {
            out.push_str("(* Sequential composition *)\n");
            out.push_str("CASE phase OF\n");
            for (idx, m) in models.iter().enumerate() {
                let mlo = m.to_lowercase();
                out.push_str(&format!("{}{} : (* Phase: {} *)\n", i1, idx, m));
                out.push_str(&format!("{}{}();\n", i2, mlo));
                out.push_str(&format!("{}IF {}.is_done THEN\n", i2, mlo));
                if idx + 1 < models.len() {
                    out.push_str(&format!("{}phase := {};\n", ctx.indent.level(3), idx + 1));
                } else {
                    out.push_str(&format!("{}phase := {};\n", ctx.indent.level(3), models.len()));
                    out.push_str(&format!("{}done := TRUE;\n", ctx.indent.level(3)));
                    if let Some(ep) = end_prop {
                        out.push_str(&format!("{}(* end handler *)\n", ctx.indent.level(3)));
                        match ep {
                            Property::Expression(e) => {
                                out.push_str(&format!("{}{} ;\n", ctx.indent.level(3), expr_to_c(e)));
                            }
                            Property::Function(s) => {
                                out.push_str(&stmt_to_c(s, &ctx.indent, 3));
                            }
                        }
                    }
                }
                out.push_str(&format!("{}END_IF;\n", i2));
                out.push('\n');
            }
            out.push_str(&format!("{}{} : (* Done *)\n", i1, models.len()));
            out.push_str(&format!("{};\n", i2));
            out.push_str("END_CASE;\n");
        }

        BehaviorKind::Parallel(_) => {
            out.push_str("(* Parallel composition *)\n");
            for m in models {
                let mlo = m.to_lowercase();
                out.push_str(&format!("{}IF NOT {}.is_done THEN\n", i1, mlo));
                out.push_str(&format!("{}{}();\n", i2, mlo));
                out.push_str(&format!("{}END_IF;\n", i1));
            }
            let all_done: Vec<String> = models.iter().map(|m| format!("{}.is_done", m.to_lowercase())).collect();
            out.push_str(&format!("IF NOT done AND {} THEN\n", all_done.join(" AND ")));
            out.push_str(&format!("{}done := TRUE;\n", i1));
            if let Some(ep) = end_prop {
                out.push_str(&format!("{}(* end handler *)\n", i1));
                match ep {
                    Property::Expression(e) => {
                        out.push_str(&format!("{}{} ;\n", i1, expr_to_c(e)));
                    }
                    Property::Function(s) => {
                        out.push_str(&stmt_to_c(s, &ctx.indent, 1));
                    }
                }
            }
            out.push_str("END_IF;\n");
        }

        BehaviorKind::Choice(_) => {
            out.push_str("(* Choice composition — executes the first selected model *)\n");
            out.push_str("IF NOT done THEN\n");
            out.push_str("CASE phase OF\n");
            for (idx, m) in models.iter().enumerate() {
                let mlo = m.to_lowercase();
                out.push_str(&format!("{}{} :\n", i1, idx));
                out.push_str(&format!("{}{}();\n", i2, mlo));
                out.push_str(&format!("{}IF {}.is_done THEN done := TRUE;", i2, mlo));
                if let Some(ep) = end_prop {
                    let ep_str = match ep {
                        Property::Expression(e) => format!(" {} ;", expr_to_c(e)),
                        Property::Function(_) => " (* end block *)".to_string(),
                    };
                    out.push_str(&ep_str);
                }
                out.push_str(&format!(" END_IF;\n"));
            }
            out.push_str("END_CASE;\n");
            out.push_str("END_IF;\n");
        }
    }

    out
}

// ── Helper functions ─────────────────────────────────────────────────────────────

fn model_name(model: &ModelDefinition) -> String {
    model.name.as_ref().map(|n| n.name.clone()).unwrap_or_else(|| "MODEL".to_string())
}

fn collect_states(model: &ModelDefinition) -> Vec<String> {
    model.parts.iter().filter_map(|p| {
        if let ModelPart::StateDefinition(sd) = p {
            sd.name.as_ref().map(|n| n.name.clone())
        } else {
            None
        }
    }).collect()
}

fn find_start(model: &ModelDefinition) -> Option<String> {
    for part in &model.parts {
        match part {
            ModelPart::PropertyDefinition(pd) => {
                if pd.name.as_ref().map(|n| n.name.as_str()) == Some("start") {
                    if let Property::Expression(but_grammar::ast::Expression::Variable(id)) = &pd.value {
                        return Some(id.name.clone());
                    }
                }
            }
            ModelPart::ConditionDefinition(cd) => {
                if cd.name.as_ref().map(|n| n.name.as_str()) == Some("start") {
                    if let Condition::Variable(id) = &cd.value {
                        return Some(id.name.clone());
                    }
                }
            }
            _ => {}
        }
    }
    None
}
