/// ARM Thumb Assembly code generator.
use but_grammar::ast::{
    Condition, ModelDefinition, ModelPart, Property, SourceUnit, SourceUnitPart, StatePart,
};

use crate::behavior::{model_composition, find_end_property, find_terminal_states, BehaviorKind};
use crate::condition::condition_to_c;
use crate::ltl::{extract_ltl_formulas, ltl_comments_thumb};
use crate::CodegenContext;

/// Generate combined ARM Thumb assembly for all models from a SourceUnit.
pub fn generate_thumb_all(source: &SourceUnit, ctx: &CodegenContext) -> String {
    let mut out = String::new();
    out.push_str("/* Generated by but-codegen (ARM Thumb) */\n");
    out.push_str("/* All models combined in one file */\n\n");
    out.push_str(".syntax unified\n");
    out.push_str(".thumb\n");
    out.push_str(".text\n\n");

    for part in &source.0 {
        if let SourceUnitPart::ModelDefinition(md) = part {
            out.push_str(&generate_thumb_model_body(md, ctx));
            out.push('\n');
        }
    }
    out
}

/// Generate ARM Thumb assembly for a single model.
pub fn generate_thumb(model: &ModelDefinition, ctx: &CodegenContext) -> String {
    let mut out = String::new();
    let ltl_formulas = extract_ltl_formulas(model);
    out.push_str("/* Generated by but-codegen (ARM Thumb) */\n");
    out.push_str(&format!("/* Model: {} */\n", model_name(model)));
    if !ltl_formulas.is_empty() {
        out.push_str(&ltl_comments_thumb(&ltl_formulas));
    }
    out.push('\n');
    out.push_str(".syntax unified\n");
    out.push_str(".thumb\n");
    out.push_str(".text\n\n");
    out.push_str(&generate_thumb_model_body(model, ctx));
    out
}

// ── Internal generation of a single model ────────────────────────────────────────

fn generate_thumb_model_body(model: &ModelDefinition, ctx: &CodegenContext) -> String {
    let ltl_formulas = extract_ltl_formulas(model);
    if let Some(bk) = model_composition(model) {
        generate_thumb_behavior(model, &bk, ctx, &ltl_formulas)
    } else {
        generate_thumb_fsm(model, ctx, &ltl_formulas)
    }
}

fn generate_thumb_fsm(
    model: &ModelDefinition,
    _ctx: &CodegenContext,
    ltl_formulas: &[String],
) -> String {
    let name = model_name(model).to_lowercase();
    let name_up = name.to_uppercase();
    let states = collect_states(model);
    let start = find_start(model).unwrap_or_else(|| states.first().cloned().unwrap_or_default());
    let start_idx = states.iter().position(|s| *s == start).unwrap_or(0);
    let terminal_states = find_terminal_states(model);
    let end_prop = find_end_property(model);

    let mut out = String::new();
    out.push_str(&format!("/* === Model: {} === */\n", name));
    if !ltl_formulas.is_empty() {
        out.push_str(&ltl_comments_thumb(ltl_formulas));
    }

    // State constants
    for (i, s) in states.iter().enumerate() {
        out.push_str(&format!(
            ".equ {}_STATE_{}, {}\n",
            name_up,
            s.to_uppercase(),
            i
        ));
    }
    // is_done flag constant
    if !terminal_states.is_empty() {
        out.push_str(&format!(".equ {}_DONE_VAL, 1\n", name_up));
    }
    out.push('\n');

    // Variables in BSS
    out.push_str(".section .bss\n");
    out.push_str(&format!("_{}_state:\n", name));
    out.push_str("    .space 4\n");
    if !terminal_states.is_empty() {
        out.push_str(&format!("_{}_done_flag:\n", name));
        out.push_str("    .space 4\n");
    }
    out.push('\n');

    out.push_str(".section .text\n\n");

    // Initialization function
    out.push_str(&format!(".global {}_init\n", name));
    out.push_str(".thumb_func\n");
    out.push_str(&format!("{}_init:\n", name));
    out.push_str(&format!("    ldr r0, =_{}_state\n", name));
    out.push_str(&format!("    movs r1, #{}\n", start_idx));
    out.push_str("    str r1, [r0]\n");
    if !terminal_states.is_empty() {
        out.push_str(&format!("    ldr r0, =_{}_done_flag\n", name));
        out.push_str("    movs r1, #0\n");
        out.push_str("    str r1, [r0]\n");
    }
    out.push_str("    bx lr\n\n");

    // is_done function
    if !terminal_states.is_empty() {
        out.push_str(&format!(".global {}_is_done\n", name));
        out.push_str(".thumb_func\n");
        out.push_str(&format!("{}_is_done:\n", name));
        out.push_str(&format!("    ldr r0, =_{}_done_flag\n", name));
        out.push_str("    ldr r0, [r0]\n");
        out.push_str("    bx lr\n\n");
    }

    // Step function
    out.push_str(&format!(".global {}_step\n", name));
    out.push_str(".thumb_func\n");
    out.push_str(&format!("{}_step:\n", name));
    out.push_str("    push {lr}\n");
    out.push_str(&format!("    ldr r0, =_{}_state\n", name));
    out.push_str("    ldr r1, [r0]  /* r1 = current state */\n\n");

    // State dispatch table
    for (idx, sname) in states.iter().enumerate() {
        out.push_str(&format!(
            "    /* Check state {} (idx={}) */\n",
            sname, idx
        ));
        out.push_str(&format!("    movs r2, #{}\n", idx));
        out.push_str("    cmp r1, r2\n");
        out.push_str(&format!(
            "    beq {}_state_{}\n",
            name,
            sname.to_lowercase()
        ));
    }
    out.push_str(&format!("    b {}_done\n\n", name));

    // State handlers
    for (idx, sname) in states.iter().enumerate() {
        let is_terminal = terminal_states.iter().any(|t| t == sname);
        out.push_str(&format!(
            "{}_state_{}:  /* State: {} */\n",
            name,
            sname.to_lowercase(),
            sname
        ));

        if let Some(ModelPart::StateDefinition(sd)) = model.parts.iter().find(|p| {
            if let ModelPart::StateDefinition(sd) = p {
                sd.name.as_ref().map(|n| n.name.as_str()) == Some(sname.as_str())
            } else {
                false
            }
        }) {
            for sp in &sd.parts {
                if let StatePart::Reference(_, target, cond) = sp {
                    let cond_str = cond
                        .as_ref()
                        .map(|c| condition_to_c(c))
                        .unwrap_or_else(|| "1".to_string());
                    let target_idx = states
                        .iter()
                        .position(|s| s == &target.name)
                        .unwrap_or(0);

                    out.push_str(&format!("    /* if ({}) → {} */\n", cond_str, target.name));
                    if let Some(Condition::Variable(id)) = cond.as_ref() {
                        out.push_str(&format!("    ldr r3, ={}\n", id.name));
                        out.push_str("    ldr r3, [r3]\n");
                    }
                    match cond.as_ref() {
                        Some(Condition::Equal(_, _, rhs)) => {
                            if let Condition::NumberLiteral(_, n) = rhs.as_ref() {
                                out.push_str(&format!("    movs r2, #{}\n", n));
                                out.push_str("    cmp r3, r2\n");
                                out.push_str(&format!(
                                    "    bne {}_state_{}_skip_{}\n",
                                    name,
                                    sname.to_lowercase(),
                                    idx
                                ));
                            }
                        }
                        Some(Condition::BoolLiteral(_, true)) | None => {}
                        _ => {
                            out.push_str("    /* complex condition — evaluate manually */\n");
                        }
                    }

                    out.push_str(&format!("    movs r1, #{}\n", target_idx));
                    out.push_str(&format!("    ldr r0, =_{}_state\n", name));
                    out.push_str("    str r1, [r0]\n");
                    out.push_str(&format!("    b {}_done\n", name));
                    out.push_str(&format!(
                        "{}_state_{}_skip_{}:\n",
                        name,
                        sname.to_lowercase(),
                        idx
                    ));
                }
            }
        }

        // Terminal state: set done
        if is_terminal {
            out.push_str(&format!("    /* Terminal state {} */\n", sname));
            out.push_str(&format!("    ldr r0, =_{}_done_flag\n", name));
            out.push_str("    movs r1, #1\n");
            out.push_str("    str r1, [r0]\n");
            if end_prop.is_some() {
                out.push_str(&format!("    bl {}_end_handler\n", name));
            }
        }

        out.push_str(&format!("    b {}_done\n\n", name));
        let _ = idx;
    }

    // end handler
    if let Some(ep) = end_prop {
        out.push_str(&format!("{}_end_handler:\n", name));
        out.push_str("    push {lr}\n");
        match ep {
            Property::Expression(e) => {
                out.push_str(&format!(
                    "    /* end: {} */\n",
                    crate::condition::expr_to_c(e)
                ));
            }
            Property::Function(_) => {
                out.push_str("    /* end block (implement manually) */\n");
            }
        }
        out.push_str("    pop {pc}\n\n");
    }

    out.push_str(&format!("{}_done:\n", name));
    out.push_str("    pop {pc}\n\n");
    out
}

fn generate_thumb_behavior(
    model: &ModelDefinition,
    bk: &BehaviorKind,
    _ctx: &CodegenContext,
    ltl_formulas: &[String],
) -> String {
    let name = model_name(model).to_lowercase();
    let name_up = name.to_uppercase();
    let models = bk.models();
    let end_prop = find_end_property(model);
    let mut out = String::new();

    out.push_str(&format!("/* === Composition model: {} === */\n", name));
    if !ltl_formulas.is_empty() {
        out.push_str(&ltl_comments_thumb(ltl_formulas));
    }

    let kind_str = match bk {
        BehaviorKind::Sequential(_) => "sequential",
        BehaviorKind::Parallel(_) => "parallel",
        BehaviorKind::Choice(_) => "choice",
    };
    out.push_str(&format!(
        "/* Composition type: {} ({}) */\n",
        kind_str,
        models.join(", ")
    ));

    // Phase constants
    for (i, m) in models.iter().enumerate() {
        out.push_str(&format!(".equ {}_PHASE_{}, {}\n", name_up, m.to_uppercase(), i));
    }
    out.push_str(&format!(".equ {}_PHASE_DONE, {}\n\n", name_up, models.len()));

    // BSS
    out.push_str(".section .bss\n");
    out.push_str(&format!("_{}_phase:\n    .space 4\n", name));
    out.push_str(&format!("_{}_done:\n    .space 4\n\n", name));
    out.push_str(".section .text\n\n");

    // init
    out.push_str(&format!(".global {}_init\n.thumb_func\n{}_init:\n", name, name));
    out.push_str("    push {lr}\n");
    for m in models {
        out.push_str(&format!("    bl {}_init\n", m.to_lowercase()));
    }
    out.push_str(&format!("    ldr r0, =_{}_phase\n", name));
    out.push_str("    movs r1, #0\n");
    out.push_str("    str r1, [r0]\n");
    out.push_str(&format!("    ldr r0, =_{}_done\n", name));
    out.push_str("    str r1, [r0]\n");
    out.push_str("    pop {pc}\n\n");

    // is_done
    out.push_str(&format!(".global {}_is_done\n.thumb_func\n{}_is_done:\n", name, name));
    out.push_str(&format!("    ldr r0, =_{}_done\n", name));
    out.push_str("    ldr r0, [r0]\n");
    out.push_str("    bx lr\n\n");

    // step
    out.push_str(&format!(".global {}_step\n.thumb_func\n{}_step:\n", name, name));
    out.push_str("    push {lr}\n");

    match bk {
        BehaviorKind::Sequential(ms) => {
            for (i, m) in ms.iter().enumerate() {
                let mlo = m.to_lowercase();
                out.push_str(&format!(
                    "    ldr r0, =_{}_phase\n    ldr r0, [r0]\n    movs r1, #{}\n    cmp r0, r1\n    bne {}_skip_{}\n",
                    name, i, name, mlo
                ));
                out.push_str(&format!("    bl {}_step\n", mlo));
                out.push_str(&format!("    bl {}_is_done\n", mlo));
                out.push_str(&format!("    cmp r0, #0\n    beq {}_comp_done\n", name));
                let next = i + 1;
                out.push_str(&format!(
                    "    ldr r0, =_{}_phase\n    movs r1, #{}\n    str r1, [r0]\n",
                    name, next
                ));
                if i + 1 == ms.len() {
                    if end_prop.is_some() {
                        out.push_str(&format!("    bl {}_end_handler\n", name));
                    }
                    out.push_str(&format!("    ldr r0, =_{}_done\n    movs r1, #1\n    str r1, [r0]\n", name));
                }
                out.push_str(&format!("{}_skip_{}:\n", name, mlo));
            }
        }
        BehaviorKind::Parallel(ms) => {
            for m in ms {
                let mlo = m.to_lowercase();
                out.push_str(&format!("    bl {}_is_done\n    cmp r0, #0\n    bne {}_par_skip_{}\n", mlo, name, mlo));
                out.push_str(&format!("    bl {}_step\n", mlo));
                out.push_str(&format!("{}_par_skip_{}:\n", name, mlo));
            }
            // Check all done
            for m in ms {
                out.push_str(&format!("    bl {}_is_done\n    cmp r0, #0\n    beq {}_comp_done\n", m.to_lowercase(), name));
            }
            if end_prop.is_some() {
                out.push_str(&format!("    bl {}_end_handler\n", name));
            }
            out.push_str(&format!("    ldr r0, =_{}_done\n    movs r1, #1\n    str r1, [r0]\n", name));
        }
        BehaviorKind::Choice(ms) => {
            if let Some(m) = ms.first() {
                let mlo = m.to_lowercase();
                out.push_str(&format!("    bl {}_step\n", mlo));
                out.push_str(&format!("    bl {}_is_done\n", mlo));
                out.push_str(&format!("    cmp r0, #0\n    beq {}_comp_done\n", name));
                if end_prop.is_some() {
                    out.push_str(&format!("    bl {}_end_handler\n", name));
                }
                out.push_str(&format!("    ldr r0, =_{}_done\n    movs r1, #1\n    str r1, [r0]\n", name));
            }
        }
    }

    out.push_str(&format!("{}_comp_done:\n    pop {{pc}}\n\n", name));

    // end handler
    if let Some(ep) = end_prop {
        out.push_str(&format!("{}_end_handler:\n    push {{lr}}\n", name));
        match ep {
            Property::Expression(e) => {
                out.push_str(&format!(
                    "    /* end: {} */\n",
                    crate::condition::expr_to_c(e)
                ));
            }
            Property::Function(_) => {
                out.push_str("    /* end block (implement manually) */\n");
            }
        }
        out.push_str("    pop {pc}\n\n");
    }

    out
}

// ── Helper functions ─────────────────────────────────────────────────────────────

fn model_name(model: &ModelDefinition) -> String {
    model.name.as_ref().map(|n| n.name.clone()).unwrap_or_else(|| "model".to_string())
}

fn collect_states(model: &ModelDefinition) -> Vec<String> {
    model.parts.iter().filter_map(|p| {
        if let ModelPart::StateDefinition(sd) = p {
            sd.name.as_ref().map(|n| n.name.clone())
        } else {
            None
        }
    }).collect()
}

fn find_start(model: &ModelDefinition) -> Option<String> {
    for part in &model.parts {
        match part {
            ModelPart::PropertyDefinition(pd) => {
                if pd.name.as_ref().map(|n| n.name.as_str()) == Some("start") {
                    if let Property::Expression(but_grammar::ast::Expression::Variable(id)) = &pd.value {
                        return Some(id.name.clone());
                    }
                }
            }
            ModelPart::ConditionDefinition(cd) => {
                if cd.name.as_ref().map(|n| n.name.as_str()) == Some("start") {
                    if let Condition::Variable(id) = &cd.value {
                        return Some(id.name.clone());
                    }
                }
            }
            _ => {}
        }
    }
    None
}
