#!/bin/sh
# Регенерация SVG-диаграмм верификации раздела «Практический пример» (фикс 0124-01).
#
# Конвейер: taktc verify --emit-graph → dot -Tsvg → svg_flatten_text.py.
# Последний шаг переводит подписи в векторные контуры наклонным ГОСТ тип А, так что
# итоговый SVG самодостаточен (шрифт при ПРОСМОТРЕ/сборке PDF не нужен). Шрифт нужен
# только здесь, на генерации — ставит `make -C book fonts`.
#
# Использование: book/scripts/render_verify_graphs.sh
set -eu

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# Каталог бинарников — у ЕДИНСТВЕННОГО носителя (фича 0301). Прежде здесь стояла
# своя копия пути, и она сломалась в день фичи 0251 (сборка переехала в
# `target/precheck`): регенерация молча не запускалась, печатала «использую
# закоммиченные SVG» и оставляла код возврата нулевым.
TAKTC="${TAKTC:-$("$ROOT/scripts/target-dir.sh")/taktc}"
MODEL="$ROOT/book/src/18-showcase/examples/lift.takt"
IMG="$ROOT/book/src/18-showcase/images"
FLATTEN="$ROOT/book/scripts/svg_flatten_text.py"
PROP="F Boarding"

# Файл шрифта — из каталога пользовательских шрифтов (ставит `make fonts`).
FONT="${GOST_FONT:-}"
if [ -z "$FONT" ]; then
    for d in "$HOME/Library/Fonts" "$HOME/.local/share/fonts"; do
        [ -f "$d/GOST2.304-81TypeA-Slanted.ttf" ] && FONT="$d/GOST2.304-81TypeA-Slanted.ttf" && break
    done
fi
[ -n "$FONT" ] || { echo "Шрифт ГОСТ не найден — выполните: make -C book fonts" >&2; exit 1; }

render() { # <kind> <файл-без-расширения> [свойство]
    kind="$1"; out="$2"; prop="${3:-}"
    if [ -n "$prop" ]; then
        "$TAKTC" verify --emit-graph "$kind" -p "$prop" "$MODEL" > "$IMG/$out.dot"
    else
        "$TAKTC" verify --emit-graph "$kind" "$MODEL" > "$IMG/$out.dot"
    fi
    # ⚠️ Строка версии graphviz ВЫЧИЩАЕТСЯ . Без этого сборка
    # документа — а она входит в предкоммит — переписывала бы committed SVG на
    # машине с другой версией `dot`: замер 2026-08-18 показал дифф из одной
    # строки `Generated by graphviz version 15.1.0 → 15.1.1` в трёх файлах.
    # Рабочее дерево не должно пачкаться от того, что у кого-то другой graphviz.
    #
    # ⚠️ Комментарий `dot` занимает ДВЕ строки: закрывающее ` -->` стоит на
    # следующей. Поэтому замена не дописывает его — иначе выходит висячий
    # `-->`, и Typst отказывается разбирать SVG (поймано сборкой документа).
    dot -Tsvg "$IMG/$out.dot" \
        | python3 "$FLATTEN" "$FONT" \
        | sed 's/^<!-- Generated by graphviz version .*$/<!-- Generated by graphviz; версия вычищена /' \
        > "$IMG/$out.svg"
    echo "  $IMG/$out.svg"
}

echo "Регенерация диаграмм верификации (наклонный ГОСТ, контуры):"
render kripke  lift-kripke
render buchi   lift-buchi   "$PROP"
render product lift-product "$PROP"
echo "Готово."
