{
    tokens = [
        ID          = "regexp:[a-zA-Z_][a-zA-z_0-9]*"
        STRING      = "regexp:\"([^\"]|\\\")*\""
        HEXSTRING   = "regexp:hex'([0-9a-fA-F][0-9a-fA-F]|_)*'|hex\"([0-9a-fA-F][0-9a-fA-F]|_)*\""
        NUMBER      = "regexp:[0-9]+"
        RATIONAL    = "regexp:[0-9]+\.[0-9]+"
        HEXNUMBER   = "regexp:0x[0-9a-fA-F]+"

        space="regexp:\s+"
        comment="regexp://.*|/\*[\s\S]*?\*/"

        // Keywords
        IMPORT      = "import"
        AS          = "as"
        FROM        = "from"
        ENUM        = "enum"
        STRUCT      = "struct"
        TYPE        = "type"
        MODEL       = "model"
        STATE       = "state"
        START       = "start"
        ABSTRACT    = "abstract"
        TEMPLATE    = "template"
        FN          = "fn"
        COND        = "cond"
        CONST       = "const"
        LET         = "let"
        MUT         = "mut"
        PORT        = "port"
        EXTERNAL    = "external"
        PRIVATE     = "private"
        TRUE        = "true"
        FALSE       = "false"
        IF          = "if"
        ELSE        = "else"
        FOR         = "for"
        WHILE       = "while"
        DO          = "do"
        CONTINUE    = "continue"
        BREAK       = "break"
        RETURN      = "return"
        ASSEMBLY    = "assembly"
        FORMULA     = "formula"
        REF         = "ref"
        IS          = "is"

        // Operators
        ARROW       = "->"
        SHARP       = "#"
        BANG        = "!"
        SEMICOLON   = ";"
        COLON       = ":"
        DOUBLECOLON = "::"
        LBRACE      = "{"
        RBRACE      = "}"
        LPAREN      = "("
        RPAREN      = ")"
        LBRACKET    = "["
        RBRACKET    = "]"
        COMMA       = ","
        DOT         = "."
        ASSIGN      = "="
        EQ          = "=="
        NEQ         = "!="
        LT          = "<"
        GT          = ">"
        LTE         = "<="
        GTE         = ">="
        OR          = "||"
        AND         = "&&"
        BITOR       = "|"
        BITAND      = "&"
        SHL         = "<<"
        SHR         = ">>"
        PLUS        = "+"
        MINUS       = "-"
        MUL         = "*"
        DIV         = "/"
        MOD         = "%"
        POW         = "**"
        INC         = "++"
        DEC         = "--"
        ADD_ASSIGN  = "+="
        SUB_ASSIGN  = "-="
        MUL_ASSIGN  = "*="
        DIV_ASSIGN  = "/="
        MOD_ASSIGN  = "%="
        OR_ASSIGN   = "|="
        AND_ASSIGN  = "&="
        SHL_ASSIGN  = "<<="
        SHR_ASSIGN  = ">>="
    ]
}

SourceUnit ::= SourceUnitPart*

SourceUnitPart ::= ImportDirective
                 | EnumDefinition
                 | StructDefinition
                 | TypeDefinition
                 | VariableDefinition
                 | GlobalAnnotationDefinition
                 | PropertyDefinition
                 | FunctionDefinition
                 | ModelDefinition
                 | FormulaDefinition
                 | SEMICOLON

ImportPath ::= STRING | ButIdentifierPath

ImportDirective ::= IMPORT ImportPath SEMICOLON
                  | IMPORT ImportPath AS ButIdentifier SEMICOLON
                  | IMPORT MUL AS ButIdentifier ID ImportPath SEMICOLON
                  | IMPORT LBRACE ImportRenameList RBRACE ID ImportPath SEMICOLON

private ImportRenameList ::= ImportRename (COMMA ImportRename)*

ImportRename ::= ButIdentifier (AS ButIdentifier)?

EnumDefinition ::= AnnotationDefinition* ENUM ButIdentifierOrError LBRACE EnumValues RBRACE

private EnumValues ::= (ButIdentifierOrError (COMMA ButIdentifierOrError)*)?

ObjectType ::= ABSTRACT | TEMPLATE

ModelDefinition ::= AnnotationDefinition* ObjectType? MODEL ButIdentifierOrError ( ASSIGN Expression )? LBRACE ModelPart* RBRACE

private ModelPart ::= EnumDefinition
            | StructDefinition
            | TypeDefinition
            | VariableDefinition
            | GlobalAnnotationDefinition
            | PropertyDefinition
            | FunctionDefinition
            | ModelDefinition
            | StateDefinition
            | FormulaDefinition
            | ConditionDefinition
            | SEMICOLON

StateDefinition ::= AnnotationDefinition* ObjectType? STATE ButIdentifierOrError ( ASSIGN Expression )? LBRACE StatePart* RBRACE

private StatePart ::= EnumDefinition
            | StructDefinition
            | TypeDefinition
            | VariableDefinition
            | GlobalAnnotationDefinition
            | PropertyDefinition
            | FunctionDefinition
            | ModelDefinition
            | FormulaDefinition
            | ConditionDefinition
            | REF Identifier ( COLON Condition )? SEMICOLON
            | SEMICOLON

ButIdentifierPath ::= ButIdentifier ( DOUBLECOLON ButIdentifier )*

Identifier ::= ID

ButIdentifier ::= ID

ButIdentifierOrError ::= ButIdentifier

ConditionDefinition ::= AnnotationDefinition* COND ButIdentifierOrError ASSIGN Condition

PropertyDefinition ::= AnnotationDefinition* ButIdentifierOrError ARROW Property

Property ::= Expression SEMICOLON | BlockStatement

VariableDeclaration ::= AnnotationDefinition* VariableAttribute* ButIdentifierOrError COLON Type

VariableDefinition ::= AnnotationDefinition* VariableAttribute* ButIdentifierOrError COLON Type ( ASSIGN Expression )? SEMICOLON

FunctionCall ::= Identifier LPAREN ExpressionList RPAREN

private ExpressionList ::= (Expression (COMMA Expression)*)?

Annotation ::= NUMBER
             | RATIONAL
             | STRING
             | ButIdentifierPath
             | TRUE
             | FALSE
             | Visibility LPAREN Expression RPAREN
             | Identifier LPAREN AnnotationOneList RPAREN
             | ButIdentifierPath ASSIGN Expression

private AnnotationOneList ::= Annotation (COMMA Annotation)*

AnnotationDefinition ::= SHARP LBRACKET AnnotationOneList RBRACKET

GlobalAnnotationDefinition ::= SHARP BANG LBRACKET AnnotationOneList RBRACKET

Visibility ::= EXTERNAL | PRIVATE

VariableAttribute ::= Visibility | CONST | LET | MUT | PORT

StructDefinition ::= AnnotationDefinition* STRUCT ButIdentifierOrError LBRACE StructFields RBRACE

private StructFields ::= (VariableDeclaration SEMICOLON)*

TypeDefinition ::= TYPE ButIdentifier ASSIGN Type SEMICOLON

private BlockStatementOrSemiColon ::= SEMICOLON | BlockStatement

FunctionDefinition ::= AnnotationDefinition* FunctionAttribute* FN ButIdentifierOrError ParameterList ( ARROW Type )? BlockStatementOrSemiColon

FunctionAttribute ::= /* empty */

FormulaDefinition ::= FORMULA STRING? FormulaBlock

Type ::= ButIdentifier
       | LBRACKET NUMBER COLON Type RBRACKET

Condition ::= Condition6

private Condition6 ::= Condition6 ASSIGN Condition5
             | Condition6 NEQ Condition5
             | Condition5

private Condition5 ::= Condition5 LT Condition4
             | Condition5 GT Condition4
             | Condition5 LTE Condition4
             | Condition5 GTE Condition4
             | Condition4

private Condition4 ::= Condition4 BITOR Condition3
             | Condition3

private Condition3 ::= Condition3 BITAND Condition2
             | Condition2

private Condition2 ::= Condition2 PLUS Condition1
             | Condition2 MINUS Condition1
             | Condition1

private Condition1 ::= BANG Condition1
             | Condition0

private Condition0 ::= Identifier
             | Identifier LPAREN ConditionList RPAREN
             | LPAREN Condition RPAREN
             | Condition0 DOT Member
             | Identifier LBRACKET NUMBER RBRACKET
             | ConditionExpression

private ConditionList ::= (Condition (COMMA Condition)*)?

ConditionExpression ::= TRUE
                      | FALSE
                      | NUMBER
                      | RATIONAL
                      | HEXNUMBER

Member ::= Identifier | NUMBER

Expression ::= Precedence14

private Precedence14 ::= Precedence13 (AssignOp Precedence14)?
private AssignOp ::= ASSIGN | OR_ASSIGN | AND_ASSIGN | SHL_ASSIGN | SHR_ASSIGN | ADD_ASSIGN | SUB_ASSIGN | MUL_ASSIGN | DIV_ASSIGN | MOD_ASSIGN

private Precedence13 ::= Precedence13 OR Precedence12
             | Precedence12

private Precedence12 ::= Precedence12 AND Precedence11
             | Precedence11

private Precedence11 ::= Precedence11 (EQ | NEQ) Precedence10
             | Precedence10

private Precedence10 ::= Precedence10 (LT | GT | LTE | GTE) Precedence9
             | Precedence9

private Precedence9 ::= Precedence9 BITOR Precedence7
             | Precedence7

private Precedence7 ::= Precedence7 BITAND Precedence6
             | Precedence7 AS Type
             | Precedence6

private Precedence6 ::= Precedence6 (SHL | SHR) Precedence5
             | Precedence5

private Precedence5 ::= Precedence5 (PLUS | MINUS) Precedence4
             | Precedence4

private Precedence4 ::= Precedence4 (MUL | DIV | MOD) Precedence3
             | Precedence3

private Precedence3 ::= Precedence2 POW Precedence3
             | Precedence2

private Precedence2 ::= BANG Precedence2
             | INC Precedence2
             | DEC Precedence2
             | PLUS Precedence2
             | MINUS Precedence2
             | Precedence1

private Precedence1 ::= NUMBER COLON NUMBER
             | NUMBER
             | RATIONAL
             | HEXNUMBER
             | LBRACE ExpressionOneList RBRACE
             | Precedence0

private ExpressionOneList ::= Expression (COMMA Expression)*

private Precedence0 ::= Identifier
             | FunctionCall
             | ParameterList
             | Precedence0 INC
             | Precedence0 DEC
             | Precedence0 DOT Member
             | Identifier LBRACKET NUMBER RBRACKET
             | Identifier LBRACKET NUMBER? COLON NUMBER? RBRACKET
             | LiteralExpression

Parameter ::= ParameterAnnotation? ButIdentifier COLON Precedence9
            | ParameterAnnotation? Precedence9

private OptParameter ::= Parameter?

ParameterList ::= LPAREN RPAREN
                | LPAREN Parameter RPAREN
                | LPAREN ParameterTwoList RPAREN

private ParameterTwoList ::= OptParameter (COMMA OptParameter)+

ParameterAnnotation ::= /* empty */

LiteralExpression ::= TRUE
                  | FALSE
                  | STRING+
                  | HEXSTRING+

BlockStatement ::= LBRACE Statement* RBRACE

Statement ::= OpenStatement
            | ClosedStatement

OpenStatement ::= IF Expression BlockStatement
                | IF Expression BlockStatement ELSE OpenStatement
                | FOR LPAREN SimpleStatement? SEMICOLON Expression? SEMICOLON Expression? RPAREN OpenStatement
                | WHILE LPAREN Expression RPAREN OpenStatement

ClosedStatement ::= NonIfStatement
                  | IF Expression BlockStatement ELSE ClosedStatement
                  | WHILE LPAREN Expression RPAREN ClosedStatement
                  | FOR LPAREN SimpleStatement? SEMICOLON Expression? SEMICOLON Expression? RPAREN ClosedStatement
                  | FOR LPAREN SimpleStatement? SEMICOLON Expression? SEMICOLON Expression? RPAREN SEMICOLON

SimpleStatement ::= VariableDeclaration ( ASSIGN Expression )?
                | Expression

NonIfStatement ::= BlockStatement
                 | ASSEMBLY STRING? BlockStatement
                 | FORMULA STRING? FormulaBlock
                 | SimpleStatement SEMICOLON
                 | DO Statement WHILE LPAREN Expression RPAREN SEMICOLON
                 | CONTINUE SEMICOLON
                 | BREAK SEMICOLON
                 | RETURN SEMICOLON
                 | RETURN Expression SEMICOLON

FormulaIdentifier ::= ID | EXTERNAL | IMPORT | IS

FormulaStatement ::= FormulaBlock
                   | FormulaFunctionCall

FormulaBlock ::= LBRACE FormulaStatement* RBRACE

FormulaLiteral ::= TRUE ( COLON FormulaIdentifier )?
                 | FALSE ( COLON FormulaIdentifier )?
                 | NUMBER ( COLON FormulaIdentifier )?
                 | HEXNUMBER ( COLON FormulaIdentifier )?
                 | HEXSTRING ( COLON FormulaIdentifier )?
                 | STRING ( COLON FormulaIdentifier )?

FormulaFunctionCall ::= FormulaIdentifier LPAREN FormulaExpressionList RPAREN

private FormulaExpressionList ::= (FormulaExpression (COMMA FormulaExpression)*)?

FormulaPath ::= FormulaIdentifier
              | FormulaPath DOT FormulaIdentifier

FormulaExpression ::= FormulaPath
                   | FormulaFunctionCall
                   | FormulaLiteral
