#!/usr/bin/env python3
"""Гейт комментариев порождённого кода (фича 0535, задача 0535-01).

Читателю вывода компилятор не рассказывает о своём устройстве. Гейт собирает
корпус `examples/*.takt` всеми целями и требует, чтобы в выводе не было
**сочинённого генератором** текста:

* `G1` - адрес решения проекта: `фича NNNN`, `ADR NNNN`, путь `scripts/...`,
  слово `precheck`. У читателя порождённого файла нет ни карточек фич, ни
  `docs/`, ни предкоммита: ссылка обещает документ, которого он не найдёт.
* `G2` - служебный маркер `NOTICE:`. Не предупреждение, не `TODO`, не
  соглашение целевого языка — слово без значения.
* `G3` - пустая строка комментария (`//`, `///`, `*` без текста). У цели `rust`
  пустой `///` — ещё и пустая doc-строка, которую `cargo doc` покажет абзацем.
* `G4` - doc-строка (`///`) в выводе цели `rust`: справку публичного API
  генератор не сочиняет (решение заказчика 2026-09-06). ⚠️ Правило переживёт
  задачу `0535-04`: авторский комментарий переносится формой `//`, а не `///`.
* `G5` - файл без шапки. Проверяется каждый файл, а не "хотя бы один":
  прежняя формулировка «шапка есть где-то» пропустила бы цель, потерявшую её
  целиком, — а до задачи `0535-02` её не печатали три цели
  (51 файл из 90).
* `G6` - в шапке есть дата. Дата сделала бы вывод невоспроизводимым, а на
  воспроизводимости стоит гейт детерминизма (фича 0048).
* `G7` - в шапке есть кириллица: постановка назвал латиницу свойством шапки
  (2026-09-06), и ключ `--lang` её не переводит.

⚠️ Запрет без положительного контроля доказывал бы лишь, что вывод пуст, —
поэтому `G5` требует шапку, а не только запрещает лишнее.

⚠️ **Комментарии АВТОРА гейт не судит** — с задачи `0535-04` они переносятся в
вывод как есть, и запреты `G1`…`G3` касаются только текста, который печатает
генератор. Отличаются они по источнику: тексты комментариев корпуса собираются
из `examples/*.takt`, и строка вывода, совпавшая с авторской, пропускается.
⚠️ Это не лазейка: автор отвечает за свой текст сам, а гейт следит за
компилятором. Класс, ради которого разделение и заведено: в примерах корпуса
авторы пишут «фича 0096» — и такой комментарий, доехав до вывода, покраснил бы
`G1`, хотя генератор ни при чём.

Самопроверка (правило 0315) — `scripts/test-check-generated-comments.sh`.
Переменная `GC_ROOT` переопределяет корень дерева (сторож гоняет гейт на копии),
`TAKTC` — путь к компилятору.
"""

import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gatelib import require_input  # noqa: E402  (путь к помощнику известен только здесь)
import tempfile
from pathlib import Path

TARGETS = ["c", "c-hal", "st", "st-at", "rust", "sv", "sv-mmio"]

# Строка вывода, начинающаяся с комментария, либо комментарий в хвосте строки.
ADDRESS = re.compile(r"(фича\s+\d{4}|ADR\s+\d{4}|scripts/[\w.-]+|precheck)")
NOTICE = re.compile(r"NOTICE")
EMPTY = re.compile(r"^\s*(///|//|\*|\(\*\s*\*\))\s*$")
RUST_DOC = re.compile(r"^\s*///")
# Шапка: единственный текст, который генератор пишет от себя (
# переработает её форму, но не факт существования).
HEADER = "Generated by the Takt compiler"
DATE = re.compile(r"\b(19|20)\d{2}[-./]\d{1,2}[-./]\d{1,2}\b")
CYRILLIC = re.compile(r"[А-Яа-яЁё]")


def author_comments(root: Path) -> set[str]:
    """Тексты комментариев корпуса — то, за что отвечает автор модели, а не компилятор."""
    texts: set[str] = set()
    for path in sorted((root / "examples").glob("*.takt")):
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            stripped = line.strip()
            for mark in ("///", "//"):
                if stripped.startswith(mark):
                    body = stripped[len(mark) :].strip()
                    if body:
                        texts.add(body)
                    break
    return texts


def build_corpus(root: Path, taktc: Path, out: Path) -> list[str]:
    """Собирает корпус всеми целями; возвращает список отказов запуска."""
    failures = []
    examples = sorted((root / "examples").glob("*.takt"))
    if not examples:
        failures.append("в дереве нет примеров examples/*.takt")
    for target in TARGETS:
        for path in examples:
            run = subprocess.run(
                [str(taktc), "compile", "-t", target, str(path), "-o", str(out / target)],
                capture_output=True,
                text=True,
            )
            # Отказ цели - её названная граница (например `SV-002`), а не дефект
            # проверки: такие примеры просто не дают файлов.
            if run.returncode not in (0, 1):
                failures.append(f"{taktc.name} {target} {path.name}: код {run.returncode}")
    return failures


def main() -> int:
    root = Path(os.environ.get("GC_ROOT", Path(__file__).resolve().parent.parent))
    taktc = Path(os.environ.get("TAKTC", root / "target" / "precheck" / "debug" / "taktc"))
    if not taktc.is_file():
        print(f"  пропуск: компилятор не собран ({taktc})")
        return 1 if os.environ.get("PRECHECK_STRICT") else 0

    errors: list[str] = []
    authored = author_comments(root)
    with tempfile.TemporaryDirectory(prefix="takt_gc_") as tmp:
        out = Path(tmp)
        errors.extend(build_corpus(root, taktc, out))

        files = [p for p in out.rglob("*") if p.is_file()]
        if not files:
            # Вырожденный вход: проверка, молчащий на пустом корпусе, ничего не
            # прочёл.
            print("ОШИБКА: корпус не собран — судить нечего", file=sys.stderr)
            return 1

        headers = 0
        for path in sorted(files):
            rel = path.relative_to(out)
            text = path.read_text(encoding="utf-8", errors="replace")
            header = header_lines(text)
            if header:
                headers += 1
                joined = "\n".join(header)
                if DATE.search(joined):
                    errors.append(f"G6 {rel}: в шапке дата — вывод перестанет быть воспроизводимым")
                if CYRILLIC.search(joined):
                    errors.append(f"G7 {rel}: шапка не на латинице — {joined.splitlines()[0]}")
            else:
                errors.append(f"G5 {rel}: файл без шапки «{HEADER}»")
            for no, line in enumerate(text.splitlines(), 1):
                if HEADER in line:
                    continue
                # Судится только текст комментария: `фича` в имени переменной
                # модели - дело автора, а не генератора.
                comment = comment_part(line, path.suffix)
                if comment is None:
                    continue
                if is_authored(comment, authored):
                    continue
                if ADDRESS.search(comment):
                    errors.append(f"G1 {rel}:{no}: адрес решения проекта — {comment.strip()}")
                if NOTICE.search(comment):
                    errors.append(f"G2 {rel}:{no}: служебный маркер — {comment.strip()}")
                if EMPTY.match(line):
                    errors.append(f"G3 {rel}:{no}: пустой комментарий")
                if path.suffix == ".rs" and RUST_DOC.match(line):
                    errors.append(f"G4 {rel}:{no}: doc-строка сочинена генератором")

        if headers == 0:
            errors.append(f"контроль: шапки «{HEADER}» нет ни в одном файле")

    if errors:
        print("Гейт комментариев порождённого кода (0535): нарушения", file=sys.stderr)
        for line in errors:
            print(f"  {line}", file=sys.stderr)
        return 1

    note = require_input("файлы порождённого кода", len(files), source="examples/generated")
    print(f"  комментарии вывода: {note}, сочинённого нет; шапок {headers}")
    return 0


def is_authored(comment: str, authored: set[str]) -> bool:
    """Написан ли этот комментарий автором модели.

    Сравнение по содержанию, а не по совпадению строки целиком: перенос снимает
    авторский маркер, ставит маркер цели и обезвреживает закрывающую
    последовательность (`*)` → `* )`), поэтому байты не совпадают.
    """
    body = comment.lstrip("/*(' ").rstrip("*)/ ").strip()
    if not body:
        return False
    if body in authored:
        return True
    # Обезвреженный текст: сравниваем, отбросив пробелы.
    squeezed = body.replace(" ", "")
    return any(squeezed == text.replace(" ", "") for text in authored)


def header_lines(text: str) -> list[str]:
    """Строки шапки файла: от строки с признаком и три подряд.

    Шапку печатает один носитель (`generator::header`), поэтому её длина
    известна; читать дальше незачем, а читать весь файл — значит спутать
    шапку с комментарием автора модели, который появится задачей `0535-04`.
    """
    lines = text.splitlines()
    for no, line in enumerate(lines[:5]):
        if HEADER in line:
            return lines[no : no + 3]
    return []


def comment_part(line: str, suffix: str) -> str | None:
    """Текст комментария в строке вывода или `None`, если его там нет.

    ⚠️ У цели `c` последовательность `(*` встречается в КОДЕ — вызов по
    указателю (`(*model->write_bit)(…)`), — поэтому форма `(* … *)` считается
    комментарием только в файлах ST.
    """
    if suffix == ".st":
        start = line.find("(*")
        return line[start:] if start >= 0 else None
    for mark in ("//", "/*"):
        start = line.find(mark)
        if start >= 0:
            return line[start:]
    return None


if __name__ == "__main__":
    sys.exit(main())
