#!/usr/bin/env bash
# Тест проверки комментариев порождённого кода.
#
# Проверка судит вывод компилятора, поэтому мутация ставится не в файл, а в
# **компилятор**: между `taktc` и проверкой встаёт обёртка, которая дописывает в
# порождённые файлы строку нужного класса. Так проверяется именно то, ради чего
# проверка заведён, - что сочинённый комментарий будет замечен в выводе.
#
# C1 - адрес решения проекта (`фича NNNN`) в комментарии;
# C2 - служебный маркер `NOTICE:`;
# C3 - пустая строка комментария;
# C4 - doc-строка `///` в выводе цели `rust`;
# C5 - нетронутый вывод принимается (иначе проверка красен всегда);
# C6 - вывод без шапки отвергается: запрет без положительного контроля
#        доказывал бы лишь, что файл пуст;
# C7 - дата в шапке (вывод перестал бы быть воспроизводимым, проверка 0048);
# C8 - кириллица в шапке ( назвал латиницу её свойством);
# C9 - комментарий автора с адресом решения пропускается: за свой текст
#        отвечает автор модели, а проверка следит за компилятором. Без этой пробы
#        различение "авторское / сочинённое" осталось бы непроверенным. Корпус
#        проекта таких комментариев не содержит, поэтому проба строит своё дерево
#        из одного примера и гоняет проверку на нём (`GC_ROOT`);
# C10 - тот же корпус, но комментарий сочинён компилятором: проба доказывает, что
#        C9 проходит из-за авторства, а не из-за подменённого корня.
set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GATE="$ROOT/scripts/check-generated-comments.py"
TAKTC="${TAKTC:-$ROOT/target/precheck/debug/taktc}"
FAILED=0

if [ ! -x "$TAKTC" ]; then
  if [ -n "${PRECHECK_STRICT:-}" ]; then
    echo "  ОШИБКА: компилятор не собран ($TAKTC) — под PRECHECK_STRICT это отказ"
    exit 1
  fi
  echo "  пропуск: компилятор не собран ($TAKTC)"
  exit 0
fi

# Обёртка над `taktc`: зовёт настоящий компилятор, затем портит вывод.
# `$1` - sed-выражение, добавляющее строку нужного класса.
make_wrapper() {
  local dir="$1" injection="$2"
  cat > "$dir/taktc" <<WRAP
#!/usr/bin/env bash
"$TAKTC" "\$@" || exit \$?
out=""
prev=""
for arg in "\$@"; do
  if [ "\$prev" = "-o" ]; then out="\$arg"; fi
  prev="\$arg"
done
[ -n "\$out" ] || exit 0
find "\$out" -type f | while read -r f; do
  $injection
done
exit 0
WRAP
  chmod +x "$dir/taktc"
}

expect() {
  local name="$1" want="$2" injection="$3"
  local dir
  dir=$(mktemp -d)
  make_wrapper "$dir" "$injection"
  TAKTC="$dir/taktc" python3 "$GATE" >/dev/null 2>&1
  local got=$?
  if [ "$want" = "fail" ] && [ "$got" -eq 0 ]; then
    echo "  ✗ $name: гейт ПРОПУСТИЛ мутацию"
    FAILED=1
  elif [ "$want" = "pass" ] && [ "$got" -ne 0 ]; then
    echo "  ✗ $name: гейт отверг корректный вывод"
    FAILED=1
  else
    echo "  ✓ $name"
  fi
  rm -rf "$dir"
}

echo "Сторож гейта комментариев порождённого кода (0535)..."

# C5 идёт первым: проверка, краснеющий на нетронутом выводе, делает бессмысленными
# все остальные пробы.
expect "C5 нетронутый вывод принимается" pass ':'
expect "C1 адрес решения проекта" fail 'printf "// пояснение (фича 0059).\n" >> "$f"'
expect "C2 служебный маркер NOTICE" fail 'printf "// NOTICE: определение\n" >> "$f"'
expect "C3 пустой комментарий" fail 'printf "//\n" >> "$f"'
expect "C4 doc-строка у цели rust" fail 'case "$f" in *.rs) printf "/// Один такт автомата.\n" >> "$f";; esac'
expect "C6 вывод без шапки отвергается" fail 'grep -v "Generated by the Takt compiler" "$f" > "$f.tmp" && mv "$f.tmp" "$f"'
expect "C7 дата в шапке" fail 'sed -i.bak "s|Generated by the Takt compiler|Generated 2026-09-06 by the Takt compiler|" "$f" && rm -f "$f.bak"'
expect "C8 кириллица в шапке" fail 'sed -i.bak "s|Do not edit by hand|Не редактировать вручную|" "$f" && rm -f "$f.bak"'
# C9 и C10 идут на своём дереве: корпус проекта комментариев с адресом решения
# больше не содержит, и на нём авторское разрешение проверить нечем.
probe_expect() {
  local name="$1" want="$2" injection="$3"
  local root dir
  root=$(mktemp -d)
  mkdir -p "$root/examples"
  printf '// пояснение (фича 0059).\nstart S;\n' > "$root/examples/probe.takt"
  dir=$(mktemp -d)
  make_wrapper "$dir" "$injection"
  GC_ROOT="$root" TAKTC="$dir/taktc" python3 "$GATE" >/dev/null 2>&1
  local got=$?
  if [ "$want" = "fail" ] && [ "$got" -eq 0 ]; then
    echo "  ✗ $name: гейт ПРОПУСТИЛ мутацию"
    FAILED=1
  elif [ "$want" = "pass" ] && [ "$got" -ne 0 ]; then
    echo "  ✗ $name: гейт отверг корректный вывод"
    FAILED=1
  else
    echo "  ✓ $name"
  fi
  rm -rf "$dir" "$root"
}

probe_expect "C9 авторский комментарий с адресом пропускается" pass ':'
probe_expect "C10 сочинённый комментарий с адресом ловится" fail 'printf "// иное пояснение (фича 0060).\n" >> "$f"'

if [ "$FAILED" -ne 0 ]; then
  echo "Сторож гейта комментариев порождённого кода: ПРОВАЛ"
  exit 1
fi
echo "Сторож гейта комментариев порождённого кода: все пробы пройдены"
