//! Шапка порождённого файла - один носитель на все цели.
//!
//! # Что в шапке и почему именно это
//!
//! Требование (2026-09-06): в самом верху - предупреждение, что файл порождён, **на
//! латинице**, с версией; **дат нет**. Отсюда три строки:
//!
//! 1. чем порождено и подо что (`taktc`, имя цели);
//! 2. что файл не правят руками - он перезаписывается;
//! 3. версия **языка** (не компилятора).
//!
//! **Версия - языка, а не компилятора**. Версия крейта растёт почти с каждой фичей (на
//! сегодня `0.60.0`), а снимки вывода лежат в дереве и сверяются проверками 0048 и 0274:
//! версия компилятора в шапке заставляла бы пересобирать 90 файлов при каждом подъёме.
//! Версия языка меняется, редко, и отвечает читателю на осмысленный вопрос - на каком
//! Takt написан исходник.
//!
//! **Даты нет** - и это не забывчивость: дата в порождённом файле сделала бы вывод
//! невоспроизводимым, а на воспроизводимости стоит проверка детерминизма, который сверяет
//! два прогона побайтно.
//!
//! **Шапка не переводится** ключом `--lang`, в отличие от комментариев автора модели:
//! назвал латиницу свойством шапки. Порождённый файл читают рядом с чужими библиотеками
//! и чужими инструментами, и техническая преамбула не должна зависеть от того, каким
//! ключом запустили компилятор.
//!
//! # Форма комментария принадлежит цели
//!
//! Текст один, а обрамление у каждого языка своё: `//` у C, Rust и SystemVerilog, `(*
//! ... *)` у Structured Text, `'` у PlantUML. Поэтому носитель отдаёт **строки
//! текста**, а обрамление накладывает [`CommentStyle`] - иначе каждая цель завела бы
//! свою копию шапки, и они разъехались бы молча.

use crate::version::LANGUAGE_VERSION;

/// Как целевой язык записывает комментарий.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CommentStyle {
    /// Построчный комментарий: `// текст` (C, Rust, SystemVerilog).
    Slashes,
    /// Блочный комментарий IEC: `(*`, ` * текст`, ` *)`.
    IecBlock,
    /// Построчный комментарий PlantUML: `' текст`.
    Quote,
}

impl CommentStyle {
    /// Обрамляет одну строку в комментарий, помещающийся в строку кода.
    ///
    /// Нужен хвостовому комментарию: блочная форма IEC многострочна, и её первая строка -
    /// голое `(*`. Приклеенная к строке кода, она открывала комментарий и не закрывала
    /// его: `iec2c` отвечал "invalid statement in ST statement", то есть вывод был
    /// Невалиден при нулевом коде возврата `taktc`.
    pub fn wrap_inline(self, text: &str) -> String {
        match self {
            Self::Slashes => format!("// {text}"),
            Self::IecBlock => format!("(* {text} *)"),
            Self::Quote => format!("' {text}"),
        }
    }

    /// Обрамляет строки текста в комментарий целевого языка.
    pub fn wrap(self, lines: &[String]) -> Vec<String> {
        match self {
            Self::Slashes => lines.iter().map(|l| format!("// {l}")).collect(),
            Self::IecBlock => {
                let mut out = vec!["(*".to_string()];
                out.extend(lines.iter().map(|l| format!(" * {l}")));
                out.push(" *)".to_string());
                out
            }
            Self::Quote => lines.iter().map(|l| format!("' {l}")).collect(),
        }
    }
}

/// Строки шапки для названной цели, уже обрамлённые комментарием.
///
/// `target` - как цель называет себя читателю ("Rust (no_std profile)", "Structured
/// Text (IEC 61131-3)"); текст **латиницей**, включая пунктуацию: порождённый файл
/// проходит через чужие инструменты (`iec2c`, старые компиляторы C), и ASCII там
/// надёжнее типографики.
pub fn file_header(target: &str, style: CommentStyle) -> Vec<String> {
    style.wrap(&[
        format!("Generated by the Takt compiler (taktc). Target: {target}."),
        "Do not edit by hand: this file is overwritten on every generation.".to_string(),
        format!("Takt language version {LANGUAGE_VERSION}."),
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Шапка называет инструмент, цель и версию языка - и ничего больше.
    #[test]
    fn header_names_tool_target_and_language_version() {
        let lines = file_header("Rust (no_std profile)", CommentStyle::Slashes);
        assert_eq!(lines.len(), 3, "{lines:?}");
        assert!(
            lines[0].contains("taktc") && lines[0].contains("Rust"),
            "{lines:?}"
        );
        assert!(lines[1].contains("Do not edit"), "{lines:?}");
        assert!(lines[2].contains(LANGUAGE_VERSION), "{lines:?}");
    }

    /// Даты в шапке нет: она сделала бы вывод невоспроизводимым (проверка 0048).
    #[test]
    fn header_carries_no_date() {
        let text = file_header("C", CommentStyle::Slashes).join("\n");
        assert!(
            !text.chars().any(|c| c.is_ascii_digit()) || !text.contains("20"),
            "в шапке не должно быть даты: {text}"
        );
    }

    /// Шапка целиком на латинице - требование 2026-09-06.
    ///
    /// Проверяется весь текст, а не "нет кириллицы в первой строке": шапку правят по
    /// частям, и незамеченное русское слово во второй строке сделало бы правило
    /// декоративным.
    #[test]
    fn header_is_latin_only() {
        for style in [
            CommentStyle::Slashes,
            CommentStyle::IecBlock,
            CommentStyle::Quote,
        ] {
            let text = file_header("Structured Text (IEC 61131-3)", style).join("\n");
            assert!(
                !text
                    .chars()
                    .any(|c| ('А'..='я').contains(&c) || c == 'ё' || c == 'Ё'),
                "шапка обязана быть латиницей: {text}"
            );
        }
    }

    /// Обрамление принадлежит цели: один текст - три формы.
    #[test]
    fn comment_style_belongs_to_the_target() {
        let slashes = file_header("C", CommentStyle::Slashes);
        assert!(slashes.iter().all(|l| l.starts_with("// ")), "{slashes:?}");

        let iec = file_header("Structured Text (IEC 61131-3)", CommentStyle::IecBlock);
        assert_eq!(iec.first().map(String::as_str), Some("(*"), "{iec:?}");
        assert_eq!(iec.last().map(String::as_str), Some(" *)"), "{iec:?}");
        assert!(
            iec[1..iec.len() - 1].iter().all(|l| l.starts_with(" * ")),
            "{iec:?}"
        );

        let quote = file_header("PlantUML", CommentStyle::Quote);
        assert!(quote.iter().all(|l| l.starts_with("' ")), "{quote:?}");
    }

    /// Блочная форма IEC не содержит закрывающей последовательности внутри.
    ///
    /// Комментарии IEC не вкладываются: `*)` внутри текста закрыл бы шапку досрочно, и
    /// остаток строки уехал бы в код - `iec2c` отверг бы файл при нулевом коде
    /// возврата.
    #[test]
    fn iec_header_has_no_early_close() {
        let lines = file_header("Structured Text (IEC 61131-3)", CommentStyle::IecBlock);
        let inner = &lines[1..lines.len() - 1];
        assert!(
            !inner.iter().any(|l| l.contains("*)")),
            "внутри блока не должно быть '*)': {inner:?}"
        );
    }
}
