@startmindmap
<style>
mindmapDiagram {
    node {
        BackgroundColor lightGreen
    }
    :depth(1) {
      BackGroundColor lightBlue
    }
}
</style>
* Type
**: **Definition**
<code>
type u8    = [8   : bit]
</code>
;
**[#FFBBCC]: **Nested**
<code>
type u32   = [32  : bit]
type int   = u32
type block2= [2 : [2: int]]
</code>
;
left side
**: **Initialize**
<code>
let mut  var6: [ 3: [3: u8] ] =
{{0, 0, 0}, {0, 0, 0}, {0, 0, 0}}
</code>
;
@endmindmap