name: pest Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Тестирование и стиль
    runs-on: ubuntu-latest
    steps:
      - name: Получение кода
        uses: actions/checkout@v2
      - name: Установка Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.56.1 # Pinned warnings
          components: rustfmt, clippy
          default: true
      - name: Установка gcc
        run: sudo apt-get update && sudo apt-get install -y gcc
      - name: Сборка
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --verbose
      - name: Тестирование
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --verbose
      - name: Документация
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --verbose
      - name: Анализ
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D warnings
      - name: Стиль
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  dependency:
    name: Тестирование
    runs-on: ubuntu-latest
    steps:
      - name: Получение кода
        uses: actions/checkout@v2
      - name: Установка gcc
        run: sudo apt-get update && sudo apt-get install -y gcc
      - name: Установка Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-01-01
          default: true
          profile: minimal
      - name: Cargo minimal-versions
        run: cargo -Z minimal-versions generate-lockfile
      - name: Тестирование
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --verbose

  coverage:
    name: Покрытие
    runs-on: ubuntu-latest
    steps:
      - name: Получение кода
        uses: actions/checkout@v3
      - name: Установка Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: llvm-tools-preview
          default: true
      - name: Установка cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Генерация
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Сохранение
        uses: codecov/codecov-action@v3
        with:
          file: lcov.info
          flags: unittests
          name: pest-ci-coverage
          fail_ci_if_error: false
          verbose: true